import CoreGraphics
import Foundation

/// Particle state required for Canvas rendering.
///
/// Generated by ``ConfettiRenderer`` from `ConfettiCloud`.
public struct ParticleRenderState: Identifiable, Sendable {
    /// Unique identifier
    public var id: UUID

    /// Drawing rectangle (scaled)
    public var rect: CGRect

    /// Fill color
    public var color: CGColor

    /// Opacity (0 to 1)
    public var opacity: Double

    /// Z-axis rotation (radians)
    public var zRotation: Double

    /// Creates a render state.
    /// - Parameters:
    ///   - id: Unique identifier
    ///   - rect: Drawing rectangle (scaled)
    ///   - color: Fill color
    ///   - opacity: Opacity (0 to 1)
    ///   - zRotation: Z-axis rotation (radians)
    public init(
        id: UUID = UUID(),
        rect: CGRect = .zero,
        color: CGColor = CGColor(gray: 0, alpha: 0),
        opacity: Double = 0,
        zRotation: Double = 0
    ) {
        self.id = id
        self.rect = rect
        self.color = color
        self.opacity = opacity
        self.zRotation = zRotation
    }
}
